openapi: 3.0.0
info:
  title: Notes API
  description: Backend service for note-taking application
  version: 0.0.1
paths:
  /notes:
    get:
      summary: Retrieve all notes
      operationId: getNotes
      responses:
        '200':
          description: All notes retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      summary: Create a new note
      operationId: createNote
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
        required: true
      responses:
        '201':
          description: Note created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
  /notes/{id}:
    get:
      summary: Retrieve a specific note by ID
      operationId: getNote
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the note
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Note retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
    put:
      summary: Update a specific note
      operationId: updateNote
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the note
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Note updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
    delete:
      summary: Delete a specific note
      operationId: deleteNote
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the note
          schema:
            type: integer
            format: int64
      responses:
        '404':
          description: Note not found

components:
  schemas:
    Note:
      type: object
      required:
        - id
        - title
        - content
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string